const translations = {
    ua: {
        buttonBack: "Назад⬅️",
        globalSheduleInfo:
            "\nНапишіть /weather, щоб побачити більше інформації про погоду🌈",
        globalErrorMessage: "Спробуйте /profile or /weather or /settings✍️",
        locationWrite: "✍️ Напишіть своє місцезнаходження:",
        locationChoose: "Виберіть своє місце розташування:👇",
        locationNotFound: "Таке розташування не знайдено, спробуйте ще раз❌",
        locationErrorRU: "Знайдено російське місто👹",
        locationCongratulations: "Чудово! Ми виявили твоє місцезнаходження✅",
        forecastButtonTomorrow: "Завтра",
        forecastButton7Days: "7 днів",
        forecastButtonMenu: "Меню",
        profileQuestion: "Що ви хочете подивитись ще?😑",
        profileButtonSettings: "Налаштування⚙️",
        profileButtonForecast: "Прогноз погоди☀️",
        registeredMessage: "Ви раніше були у нас у базі🐠",
        registeredQuestion: (location) =>
            `На сьогодні, ви знаходитесь в ${location}❓`,
        registeredButtonYes: "Так",
        registeredButtonNo: "Ні",
        settingsEnterQuestion: "Що ви хочете змінити?⚙️",
        settingsButtonLocations: "Розташування🇺🇦",
        settingsButtonLang: "Мова інтерфейсу💬",
        settingsButtonNotifications: "Сповіщення🔔",
        settingsLanguageQuestion: "Оберіть мову:",
        settingsLanguageButtonUA: "Українська",
        settingsLanguageButtonRU: "Російська",
        settingsLanguageButtonEN: "Англійська",
        settingsNotificationsQuestion:
            "Вибери час, коли хочеш отримувати повідомлення про прогноз погоди:⏳",
        settingsNotificationsButtonTRUE: "Включити повідомлення🌝",
        settingsNotificationsButtonFALSE: "Вимкнути повідомлення🌚",
        settingsSuccess: "Успешно сохранено✅",
    },
    ru: {
        buttonBack: "Назад⬅️",
        globalSheduleInfo:
            "\nНапишите /weather, чтобы увидеть больше информации о погоде🌈",
        globalErrorMessage: "Попробуйте /profile or /weather or /settings✍️",
        locationWrite: "✍️ Напишите свое местоположение",
        locationChoose: "Выберите свое местоположение:👇",
        locationNotFound:
            "Такое местоположение не найдено, попробуйте еще раз❌",
        locationErrorRU: "Найден российский город👹",
        locationCongratulations: "Круто! Мы нашли твое местоположение✅",
        forecastButtonTomorrow: "Завтра",
        forecastButton7Days: "7 дней",
        forecastButtonMenu: "Меню",
        profileQuestion: "Что вы хотите посмотреть еще?😑",
        profileButtonSettings: "Настройки⚙️",
        profileButtonForecast: "Прогноз погоды☀️",
        registeredMessage: "Вы ранее были у нас в базе🐠",
        registeredQuestion: (location) =>
            `На сейчас, вы находитесь в ${location}❓`,
        registeredButtonYes: "Да",
        registeredButtonNo: "Нет",
        settingsEnterQuestion: "Что вы хотите изменить?⚙️",
        settingsButtonLocations: "Местонахождения🇺🇦",
        settingsButtonLang: "Язык интерфейса💬",
        settingsButtonNotifications: "Уведомления🔔",
        settingsLanguageQuestion: "Выберите язык:",
        settingsLanguageButtonUA: "Украинский",
        settingsLanguageButtonRU: "Русский",
        settingsLanguageButtonEN: "Английский",
        settingsNotificationsQuestion:
            "Выбери время, когда хочешь получать уведомление о прогнозе погоды:⏳",
        settingsNotificationsButtonTRUE: "Включить уведомления🌝",
        settingsNotificationsButtonFALSE: "Выключить уведомления🌚",
        settingsSuccess: "Успешно сохранено✅",
    },
    en: {
        buttonBack: "Back⬅️",
        globalSheduleInfo: "\nWrite /weather to see more weather forecast🌈",
        globalErrorMessage: "Try /profile or /weather or /settings✍️",
        locationWrite: "✍️ Write your location:",
        locationChoose: "Choose your location:👇",
        locationNotFound: "Such location are not found, try again❌",
        locationCongratulations: "Nice! We've got your location✅",
        locationErrorRU: "Russian city found👹",
        forecastButtonTomorrow: "Tomorrow",
        forecastButton7Days: "7 days",
        forecastButtonMenu: "Menu",
        profileQuestion: "What do you want to see more?😑",
        profileButtonSettings: "Settings⚙️",
        profileButtonForecast: "Weather forecast☀️",
        registeredMessage: "You were previously in our database🐠",
        registeredQuestion: (location) => `Your location is ${location}, now❓`,
        registeredButtonYes: "Yes",
        registeredButtonNo: "No",
        settingsEnterQuestion: "What do you want to change?⚙️",
        settingsButtonLocations: "Location🇺🇦",
        settingsButtonLang: "Interface language💬",
        settingsButtonNotifications: "Notifications🔔",
        settingsLanguageQuestion: "Choose language:",
        settingsLanguageButtonUA: "Ukrainian",
        settingsLanguageButtonRU: "Russian",
        settingsLanguageButtonEN: "English",
        settingsNotificationsQuestion:
            "Select the time when you want to receive a weather forecast notification:⏳",
        settingsNotificationsButtonTRUE: "Enable Notifications🌝",
        settingsNotificationsButtonFALSE: "Turn off notifications🌚",
        settingsSuccess: "Saved successfully✅",
    },
};

export default translations;
